version: "3"

networks:
  laravel:

services:
  # nginx:
  #   image: nginx
  #   container_name : nginx
  #   ports:
  #     - 8080:80
  #   links:
  #     - ems-docker
  #   volumes:
  #     - ./event-management-system:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - ems-docker
  #     - mysql_db
  #   networks:
  #     - laravel

  ems-docker:
    container_name: ems-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./event-management-system:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
      
  mysql_db:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_USERNAME: root
      MYSQL_DATABASE: event_management_system
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./event-management-system:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./event-management-system:/var/www/html
    depends_on:
      - mysql_db
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/artisan"]
    networks:
      - laravel
